### ISSUE TITLE
Change package name in build.zig.zon

### ISSUE THREAD

**Issue by bauripalash** [desttinghim/zig-libui-ng#8]
While installing the library with `zig fetch` the package name is set to `trex`. I recommend changing this to something reasonable such as `zig_libui_ng` or something like that. 

Only changing this line is required 

https://github.com/desttinghim/zig-libui-ng/blob/975241aeec9cca10b809134b70b407f42aab2268/build.zig.zon#L2

**Comment by desttinghim** [comment]
Thanks for making this issue! I've pushed a fix.
